name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-23.05
    - uses: cachix/cachix-action@v12
      with:
        name: 24d404c2031ae73edd0f9ad209bb5d0a
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build .#nixosConfigurations.exampleIso.config.system.build.isoImage
